### ISSUE TITLE
Implement rtrees with clustering optimization

### ISSUE THREAD

**Issue by peterg17** [tracyhenry/Kyrix#110]
Aka wenbo's funky rtrees.
The basic idea of this is that we will use the GiST box type, which postgres will index as a normal rtree. The main difference between this and our PsqlNativeBoxIndexer is that we take bounding boxes that are close to each other and put them into the same row.

**Comment by asah** [comment]
Yes - native is multiplicatively faster because you're not moving each
record out to the Kyrix middleware during indexing, but instead executing
the JavaScript transform function inside of Postgres. This also supports
scale-up a.k.a. parallel indexing across a cluster (e.g. Citus) vs moving
each record to a single Kyrix middleware instance.

**Comment by tracyhenry** [comment]
Peter, I don't have other papers in mind but I will send you if I come across any. Feel free to research a bit (e.g. just google clustering algorithms, since this idea works with any 2D clustering schemes). Writing down possible approaches will be great. Also, it'll be good if you can help test this indexer and see what its performance is in your testing environment. It should be relatively faster on 100M records compared to 2D indexer, both in index and online performance. 

Adam brought up a good point: how to avoid moving each record out of the database to Java back-end. The current grid indexer doesn't avoid it. Although being simple, it requires pretty heavy manipulation of raw records, e.g. concatenating fields, calculating grid coordinates, etc. Writing custom JS functions and push the manipulations into Postgres would be interesting and should boost index performance.
