### ISSUE TITLE
NBA example / box scores: display placement is absolute, causing cropping on small windows

### ISSUE THREAD

**Issue by asah** [tracyhenry/Kyrix#44]
![image](https://user-images.githubusercontent.com/140002/48671697-2a61a000-eb67-11e8-86da-18eafd6964fe.png)

examples/nba/placements.js:14 looks suspicious?
boxscorePlacement.centroid_x = "con:1000";
boxscorePlacement.centroid_y = "con:500";

**Comment by tracyhenry** [comment]
This cropping is expected, since the viewport size is fixed at 1000*1000. If you have a screen size smaller than that, you have to use browser-scroll to see everything. 

You are right that this placement is not accurate, but it actually works (I was lazy)... The reason is that it specifies a box that spans the whole x axis, so it will intersect the viewport (no matter where it is) and make frontend fetch everything from backend. 

But I'll change it to be accurate.

**Comment by tracyhenry** [comment]
Whether the viewport is fix-sized is another thing. I gave it many thoughts and think that a fix-sized is better and easier to specify things, especially given in the future we will incorporate multiple coordinated views (which we are doing for mgh now). We can talk about this more after you get enough context.
