### ISSUE TITLE
decouple indexing from createMV in indexers

### ISSUE THREAD

**Issue by peterg17** [tracyhenry/Kyrix#71]
Essentially, because 3D indexing adds to the same table between canvases, I had trouble where the createMV function would overwrite the same index for each canvas. I solved this by building a workaround where I made a separate function for just the 3D rtree indexer, but I think that we should decouple the indexing from the other operations in createMV so this is more clean and well done. I understand this issue and can do it.

**Comment by asah** [comment]
I'd like to learn more - I'm also making big changes to createMV.

Perhaps the 3D index could be created after the per-layer indexes?

Anyway, the sooner I can see code the better: I'll be working to
parallelize this across the cluster.

Adam

(via cellphone, random spelling ahead)

**Comment by tracyhenry** [comment]
sorry, I can't quite understand what the issue is.

`createMV()` is called per layer. As we talked, you can still follow this by just only create table/index for layers that are not on the top-level, similar to what I did for my [autoDDIndexer](https://github.com/tracyhenry/Kyrix/blob/auto_dd/back-end/src/main/java/index/AutoDDIndexer.java#L38)

Is this what this issue is about?

**Comment by tracyhenry** [comment]
@peterg17  per discussion yesterday, we will find ways to infer whether a canvas is on the top/bottom level, to help decide whether to create index for this canvas. This will keep the current structure (i.e. indexing is still done in `createMV`).
